ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  TYPE: "iGibsonSocialNav"
  AGENT_0:
    SENSORS: ['RGB_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: True # True or False
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  NUM_PEOPLE: 0 # set to 1 or more to generate people in scene
  PEOPLE_LIN_SPEED: 0.25
  PEOPLE_ANG_SPEED: 10.0
  TIME_STEP: 1.0
TASK:
  TYPE: SocialNav-v0
  SUCCESS_DISTANCE: 0.2

  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOCIAL_TOP_DOWN_MAP', 'HUMAN_COLLISION']
  SUCCESS:
    SUCCESS_DISTANCE: 0.2

  #POSSIBLE_ACTIONS: ["VELOCITY_CONTROL"] # this is automatically set for gaussian action distribution in ppo_trainer.py when using gaussian action distribution. Needs to be set manually for using demo.py

DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  DATA_PATH: data/datasets/pointnav/room3x3/v0/{split}/{split}.json.gz
